language: rust

cache: cargo

matrix:
  fast_finish: true
  include:
    - rust: stable
      script:
        - cargo test --release
        - cargo check --examples --all 
        - cargo check --all-features --examples --all

    - rust: nightly
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
        - cargo test --release
        - cargo check --examples --all --benches
        - cargo check --all-features --examples --all --benches

    - rust: stable
      install:
        - rustup target add thumbv6m-none-eabi
      env: RUSTFLAGS='-C target-cpu=cortex-a7'
      script:
        # test algebra
        - cargo check --examples --no-default-features --target thumbv6m-none-eabi
        - cargo build --no-default-features --target thumbv6m-none-eabi
